# Generated by Django 2.1 on 2019-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_login', '0002_auto_20190328_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='face_encode',
            field=models.TextField(),
        ),
    ]
