# Generated by Django 2.1 on 2019-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_login', '0003_auto_20190328_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faces',
            name='face_encode',
        ),
        migrations.AddField(
            model_name='faces',
            name='face_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
