# Generated by Django 2.1 on 2019-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_login', '0004_auto_20190328_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='face_img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
